import { createHash } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { defineConfig, type Plugin } from 'vite'

// Writes dist/sw.js after the build: it precaches the built files so the page opens
// without a network. The cache name hashes their contents, so every deploy that changes
// a file also changes sw.js and replaces the old cache.
function offlineWorker(): Plugin {
  return {
    name: 'crackcheck-offline-worker',
    apply: 'build',
    writeBundle(options, bundle) {
      const files = Object.keys(bundle).sort()
      const hash = createHash('sha256')
      for (const name of files) {
        const output = bundle[name]
        hash.update(name).update(output.type === 'chunk' ? output.code : output.source)
      }
      const cache = `crackcheck-${hash.digest('hex').slice(0, 16)}`
      const urls = ['./', ...files.filter(name => name !== 'index.html').map(name => `./${name}`)]
      writeFileSync(join(options.dir ?? 'dist', 'sw.js'), `// Generated by vite.config.ts. Caches only this site's own static files.
const CACHE = ${JSON.stringify(cache)}
const URLS = ${JSON.stringify(urls)}.map(url => new URL(url, self.location).href)
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(URLS)).then(() => self.skipWaiting()))
})
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()))
})
self.addEventListener('fetch', event => {
  const request = event.request
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return
  // Pages are network-first so a deploy shows on the next load; the cache is the offline fallback.
  // Hashed assets are cache-first: a new page asks for new names, which miss the cache and go to the network.
  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).catch(() => caches.open(CACHE).then(async cache =>
      await cache.match(request, { ignoreVary: true, ignoreSearch: true }) || await cache.match(URLS[0], { ignoreVary: true }))))
    return
  }
  event.respondWith(caches.open(CACHE).then(cache => cache.match(request, { ignoreVary: true })).then(cached => cached || fetch(request)))
})
`)
    },
  }
}

export default defineConfig({
  base: process.env.GITHUB_PAGES === 'true' ? '/crackcheck/' : '/',
  plugins: [offlineWorker()],
  build: { rolldownOptions: { input: { main: 'index.html', business: 'business.html' } } },
})
